#!/bin/bash

set -o errexit -o pipefail -o noclobber

input=${1}
N=${2:-1}
decompress=false

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z ${input} ]; then
    echo "Usage: $0 [OPTION]... DIRECTORY"
    exit 1
fi


function compress {
    find "${input}" -name "*.fast5" | \
	xargs ${SCRIPT_DIR}/fast5vbz.py -t "${N}" | \
	xargs -P "${N}" -I % sh -c "h5repack -i % -o %.tmp && mv %.tmp %"
}


function decompress {
    find "${input}" -name "*.fast5" | \
	xargs ${SCRIPT_DIR}/fast5vbz.py -t "${N}" -d | \
	xargs -P "${N}" -I % sh -c "h5repack -f GZIP=1 -i % -o %.tmp && mv %.tmp %"
}


function main {
    presize=$(du -s "${input}" | awk '{print $1}')
    
    if $decompress; then
	echo "Decompressing..."
	decompress
    else
	echo "Compressing..."
	compress
    fi

    postsize=$(du -s "${input}" | awk '{print $1}')
    awk -v b=${presize} -v a=${postsize} 'BEGIN{printf "Compression Ratio %.2f\n", (a/b)}'
}

main
